'use strict';

module.exports = function(grunt) {
	grunt.initConfig({
		typescript:{
			base:{
				src:['jThree/src/jThree.ts'],
				dest:'jThree/jThree.js',
				options:{
					comments:true,
					target:'es5'
				}

			}
		},
		qunit:{
			all:{
				options:{
					urls:[
						'http://localhost:8081/jThree/test/MathTest.html'
					]
				}
			}
		},
		connect:{
		local:{
				options:{
					port:8081
			}
		}
		},
		blanket_qunit:{
			all:{
				options:{
					urls:['http://localhost:8081/jThree/test/MathTest.html?coverage=true&gruntReport'],
					threshold:20
				}
			}
		}
	});
	grunt.loadNpmTasks('grunt-typescript');
	grunt.loadNpmTasks('grunt-contrib-qunit');
	grunt.loadNpmTasks('grunt-contrib-connect');
	grunt.loadNpmTasks('grunt-blanket-qunit');
	grunt.registerTask('travis',['typescript','connect','blanket_qunit']);
	grunt.registerTask('compile',['typescript']);
	grunt.registerTask('server',['connect']);
	grunt.registerTask('default',['typescript','connect','blanket_qunit']);
};
